name: Publish to GitHub Packages and npmjs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@elastic2ls-com'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npmjs:
    name: Publish to npmjs.com
    runs-on: ubuntu-latest
    needs: publish-github

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for npmjs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npmjs
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

